/* eslint-disable @nx/enforce-module-boundaries */
import { Footer, Navbar } from '@lookin-app/common-components';
import './global.css';
import '../../../../shared-assets/styles/fonts.css'; 
export const metadata = {
  title: 'Welcome to itservices-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
           <head>
          
            </head> 
      <body>
        
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
