import './global.css';

export const metadata = {
  title: 'Welcome to home-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <script src="https://unpkg.com/flowbite@1.4.1/dist/flowbite.js"></script>
      </head>
      <body>
        
        {children}</body>
    </html>
  );
}
